/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_Kelola;

import Connection.connection;
import Form_Menu.Form_Menu_Admin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luckycious
 */
public class Form_Personalia extends javax.swing.JFrame {

    public Connection con;
    public PreparedStatement pst;
    public Form_Personalia() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampil_tabel_personalia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        tambahDataPegawai = new javax.swing.JLabel();
        personalia = new javax.swing.JLabel();
        farmasi = new javax.swing.JLabel();
        keuangan = new javax.swing.JLabel();
        report = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        label_nim = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();
        label_nim1 = new javax.swing.JLabel();
        text_nm = new javax.swing.JTextField();
        text_alt = new javax.swing.JTextField();
        label_nim2 = new javax.swing.JLabel();
        text_jk = new javax.swing.JTextField();
        label_nim3 = new javax.swing.JLabel();
        label_nim4 = new javax.swing.JLabel();
        text_tl = new javax.swing.JTextField();
        label_nim5 = new javax.swing.JLabel();
        text_telp = new javax.swing.JTextField();
        text_dept = new javax.swing.JTextField();
        label_nim6 = new javax.swing.JLabel();
        text_gaji = new javax.swing.JTextField();
        label_nim7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_personalia = new javax.swing.JTable();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        text_search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(46, 54, 117));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/welcome.png"))); // NOI18N

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Kelola Data Personalia");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Welcome, ");

        home.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        tambahDataPegawai.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tambahDataPegawai.setForeground(new java.awt.Color(255, 255, 255));
        tambahDataPegawai.setText("Tambah Data Pegawai");
        tambahDataPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahDataPegawaiMouseClicked(evt);
            }
        });

        personalia.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        personalia.setForeground(new java.awt.Color(255, 255, 255));
        personalia.setText("Personalia");
        personalia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personaliaMouseClicked(evt);
            }
        });

        farmasi.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        farmasi.setForeground(new java.awt.Color(255, 255, 255));
        farmasi.setText("Farmasi");
        farmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                farmasiMouseClicked(evt);
            }
        });

        keuangan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        keuangan.setForeground(new java.awt.Color(255, 255, 255));
        keuangan.setText("Keuangan");
        keuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keuanganMouseClicked(evt);
            }
        });

        report.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setText("Report");
        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tambahDataPegawai)
                        .addGap(28, 28, 28)
                        .addComponent(personalia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(farmasi)
                        .addGap(26, 26, 26)
                        .addComponent(keuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home)
                    .addComponent(tambahDataPegawai)
                    .addComponent(personalia)
                    .addComponent(farmasi)
                    .addComponent(keuangan)
                    .addComponent(report))
                .addGap(13, 13, 13))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tambah Data Personalia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(46, 54, 117))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(1, 50, 67));

        label_nim.setBackground(new java.awt.Color(46, 54, 117));
        label_nim.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim.setForeground(new java.awt.Color(46, 54, 117));
        label_nim.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim.setText("ID Pegawai");

        text_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idActionPerformed(evt);
            }
        });

        label_nim1.setBackground(new java.awt.Color(46, 54, 117));
        label_nim1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim1.setForeground(new java.awt.Color(46, 54, 117));
        label_nim1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim1.setText("Nama Karyawan");

        text_nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nmActionPerformed(evt);
            }
        });

        text_alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_altActionPerformed(evt);
            }
        });

        label_nim2.setBackground(new java.awt.Color(46, 54, 117));
        label_nim2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim2.setForeground(new java.awt.Color(46, 54, 117));
        label_nim2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim2.setText("Alamat");

        text_jk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_jkActionPerformed(evt);
            }
        });

        label_nim3.setBackground(new java.awt.Color(46, 54, 117));
        label_nim3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim3.setForeground(new java.awt.Color(46, 54, 117));
        label_nim3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim3.setText("Jenis Kelamin");

        label_nim4.setBackground(new java.awt.Color(46, 54, 117));
        label_nim4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim4.setForeground(new java.awt.Color(46, 54, 117));
        label_nim4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim4.setText("Tanggal Lahir");

        text_tl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tlActionPerformed(evt);
            }
        });

        label_nim5.setBackground(new java.awt.Color(46, 54, 117));
        label_nim5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim5.setForeground(new java.awt.Color(46, 54, 117));
        label_nim5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim5.setText("No Telp");

        text_telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_telpActionPerformed(evt);
            }
        });

        text_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_deptActionPerformed(evt);
            }
        });

        label_nim6.setBackground(new java.awt.Color(46, 54, 117));
        label_nim6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim6.setForeground(new java.awt.Color(46, 54, 117));
        label_nim6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim6.setText("Department");

        text_gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_gajiActionPerformed(evt);
            }
        });

        label_nim7.setBackground(new java.awt.Color(46, 54, 117));
        label_nim7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim7.setForeground(new java.awt.Color(46, 54, 117));
        label_nim7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim7.setText("Gaji");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_nm, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_jk, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_tl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_jk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_tl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabel Data Personalia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(46, 54, 117))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(1, 50, 67));

        tabel_personalia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabel_personalia.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tabel_personalia.setForeground(new java.awt.Color(46, 54, 117));
        tabel_personalia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Pegawai", "Nama Lengkap", "Alamat", "Jenis Kelamin", "Tanggal Lahir", "No Telp", "Departemen", "Gaji"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel_personalia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_personaliaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_personalia);

        saveBtn.setBackground(new java.awt.Color(46, 54, 117));
        saveBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.setPreferredSize(new java.awt.Dimension(65, 32));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(46, 54, 117));
        updateBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(46, 54, 117));
        deleteBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(46, 54, 117));
        resetBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        text_search.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        text_search.setForeground(new java.awt.Color(46, 54, 117));
        text_search.setText("Search...");
        text_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_searchMouseClicked(evt);
            }
        });
        text_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addComponent(text_search)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idActionPerformed

    private void text_nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nmActionPerformed

    private void text_altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_altActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_altActionPerformed

    private void text_jkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_jkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_jkActionPerformed

    private void text_tlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tlActionPerformed

    private void text_telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_telpActionPerformed

    private void text_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_deptActionPerformed

    private void text_gajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_gajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_gajiActionPerformed

    private void text_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_searchActionPerformed
        pencarian_personalia();
    }//GEN-LAST:event_text_searchActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String idPegawai = "", namaLengkap = "", alamat = "", jenisKlamin = "", tanggalLahir = "", noTelp = "", departemen = "", gaji = "";

        idPegawai = text_id.getText();
        namaLengkap = text_nm.getText();
        alamat = text_alt.getText();
        jenisKlamin = text_jk.getText();
        tanggalLahir = text_tl.getText();
        noTelp = text_telp.getText();
        departemen = text_dept.getText();
        gaji = text_gaji.getText();

        con = connection.getConnection();
        try {
            String sql = "insert into tabel_personalia values (?,?,?,?,?,?,?,?)";
            PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);

            stat.setString(1, idPegawai);
            stat.setString(2, namaLengkap);
            stat.setString(3, alamat);
            stat.setString(4, jenisKlamin);
            stat.setString(5, tanggalLahir);
            stat.setString(6, noTelp);
            stat.setString(7, departemen);
            stat.setString(8, gaji);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Menyimpan data BERHASIL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            reset();
            tampil_tabel_personalia();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menyimpan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        con = connection.getConnection();
        String idPegawai = "", namaLengkap = "", alamat = "", jenisKlamin = "", tanggalLahir = "", noTelp = "", departemen = "", gaji = "";

        idPegawai = text_id.getText();
        namaLengkap = text_nm.getText();
        alamat = text_alt.getText();
        jenisKlamin = text_jk.getText();
        tanggalLahir = text_tl.getText();
        noTelp = text_telp.getText();
        departemen = text_dept.getText();
        gaji = text_gaji.getText();

        if (namaLengkap == null) {
            JOptionPane.showMessageDialog(null, "Silahkan isi Nama Lengkap anda", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String sql = "update tabel_personalia set namaLengkap=?, alamat=?, jenisKlamin=?, tanggalLahir=?, noTelp=?, departemen=?, gaji=? where idPegawai='" + idPegawai + "'";
            java.sql.PreparedStatement stat = null;
            try {
                stat = con.prepareStatement(sql);
                stat.setString(1, namaLengkap);
                stat.setString(2, alamat);
                stat.setString(3, jenisKlamin);
                stat.setString(4, tanggalLahir);
                stat.setString(5, noTelp);
                stat.setString(6, departemen);
                stat.setString(7, gaji);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data BERHASIL di Ubah");
                tampil_tabel_personalia();
                reset();
            } catch (SQLException se) {
                JOptionPane.showMessageDialog(null, "Data GAGAL di Ubah");
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int baris = tabel_personalia.getSelectedRow();
        String idPegawai = tabmode.getValueAt(baris, 0).toString();
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data idPegawai: " + idPegawai + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                con = connection.getConnection();
                String sql = "delete from tabel_personalia where idPegawai='" + idPegawai + "'";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil di hapus");
                tampil_tabel_personalia();
                reset();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal di hapus");
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        reset();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Form_Menu_Admin rgs = new Form_Menu_Admin();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void tambahDataPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahDataPegawaiMouseClicked
        Form_Tambah_Data_Pegawai rgs = new Form_Tambah_Data_Pegawai();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_tambahDataPegawaiMouseClicked

    private void personaliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personaliaMouseClicked
        Form_Personalia rgs = new Form_Personalia();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_personaliaMouseClicked

    private void farmasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_farmasiMouseClicked
        Form_Farmasi rgs = new Form_Farmasi();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_farmasiMouseClicked

    private void keuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keuanganMouseClicked
        Form_Keuangan rgs = new Form_Keuangan();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_keuanganMouseClicked

    private void reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseClicked
        Form_Report rgs = new Form_Report();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_reportMouseClicked

    private void tabel_personaliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_personaliaMouseClicked
        kliktable();
    }//GEN-LAST:event_tabel_personaliaMouseClicked

    private void text_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_searchMouseClicked
        text_search.setText("");
    }//GEN-LAST:event_text_searchMouseClicked
    
    public void pencarian_personalia() {
        String cari = text_search.getText();

        Object[] Baris = {"idPegawai", "namaLengkap", "alamat", "jenisKlamin", "tanggalLahir", "noTelp", "departemen", "gaji"};
        tabmode = new DefaultTableModel(null, Baris);
        tabel_personalia.setModel(tabmode);

        con = connection.getConnection();

        try {
            String sql = "Select * from tabel_personalia where "
                    + "idPegawai like '%" + cari + "%' "
                    + "OR namaLengkap like '%" + cari + "%' "
                    + "OR alamat like '%" + cari + "%' "
                    + "OR jenisKlamin like '%" + cari + "%' "
                    + "OR tanggalLahir like '%" + cari + "%' "
                    + "OR noTelp like '%" + cari + "%' "
                    + "OR departemen like '%" + cari + "%' "
                    + "OR gaji like '%" + cari + "%' "
                    + "order by idPegawai asc";
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                String idPegawai = rslt.getString("idPegawai");
                String namaLengkap = rslt.getString("namaLengkap");
                String alamat = rslt.getString("alamat");
                String jenisKlamin = rslt.getString("jenisKlamin");
                String tanggalLahir = rslt.getString("tanggalLahir");
                String noTelp = rslt.getString("noTelp");
                String departemen = rslt.getString("departemen");
                String gaji = rslt.getString("gaji");

                String[] dataField = {idPegawai, namaLengkap, alamat, jenisKlamin, tanggalLahir, noTelp, departemen, gaji};
                tabmode.addRow(dataField);
            }
        } catch (Exception ex) {
        }
    }

    public void reset() {
        text_id.setText("");
        text_nm.setText("");
        text_alt.setText("");
        text_jk.setText("");
        text_tl.setText("");
        text_telp.setText("");
        text_dept.setText("");
        text_gaji.setText("");
    }

    private void kliktable() {
        int baris = tabel_personalia.getSelectedRow();
        text_id.setText((String) tabel_personalia.getValueAt(baris, 0));
        text_nm.setText((String) tabel_personalia.getValueAt(baris, 1));
        text_alt.setText((String) tabel_personalia.getValueAt(baris, 2));
        text_jk.setText((String) tabel_personalia.getValueAt(baris, 3));
        text_tl.setText((String) tabel_personalia.getValueAt(baris, 4));
        text_telp.setText((String) tabel_personalia.getValueAt(baris, 5));
        text_dept.setText((String) tabel_personalia.getValueAt(baris, 6));
        text_gaji.setText((String) tabel_personalia.getValueAt(baris, 7));
    }

    private DefaultTableModel tabmode;

    public void tampil_tabel_personalia() {
        Object[] baris = {"idPegawai", "namaLengkap", "alamat", "jenisKlamin", "tanggalLahir", "noTelp", "departemen", "gaji"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_personalia.setModel(tabmode);
        con = connection.getConnection();
        try {
            String sql = "select * from tabel_personalia order by idPegawai asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet rslt = stat.executeQuery(sql);
            while (rslt.next()) {
                String idPegawai = rslt.getString("idPegawai");
                String namaLengkap = rslt.getString("namaLengkap");
                String alamat = rslt.getString("alamat");
                String jenisKlamin = rslt.getString("jenisKlamin");
                String tanggalLahir = rslt.getString("tanggalLahir");
                String noTelp = rslt.getString("noTelp");
                String departemen = rslt.getString("departemen");
                String gaji = rslt.getString("gaji");
                String[] data = {idPegawai, namaLengkap, alamat, jenisKlamin, tanggalLahir, noTelp, departemen, gaji};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Personalia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Personalia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Personalia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Personalia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Personalia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel farmasi;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel keuangan;
    private javax.swing.JLabel label_nim;
    private javax.swing.JLabel label_nim1;
    private javax.swing.JLabel label_nim2;
    private javax.swing.JLabel label_nim3;
    private javax.swing.JLabel label_nim4;
    private javax.swing.JLabel label_nim5;
    private javax.swing.JLabel label_nim6;
    private javax.swing.JLabel label_nim7;
    private javax.swing.JLabel personalia;
    private javax.swing.JLabel report;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable tabel_personalia;
    private javax.swing.JLabel tambahDataPegawai;
    private javax.swing.JTextField text_alt;
    private javax.swing.JTextField text_dept;
    private javax.swing.JTextField text_gaji;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_jk;
    private javax.swing.JTextField text_nm;
    private javax.swing.JTextField text_search;
    private javax.swing.JTextField text_telp;
    private javax.swing.JTextField text_tl;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
