/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_Kelola;

import Connection.connection;
import Form_Menu.Form_Menu_Admin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luckycious
 */
public class Form_Tambah_Data_Pegawai extends javax.swing.JFrame {

    public Connection con;
    public PreparedStatement pst;
    
    public Form_Tambah_Data_Pegawai() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampil_tabel_karyawan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        tambahDataPegawai = new javax.swing.JLabel();
        personalia = new javax.swing.JLabel();
        farmasi = new javax.swing.JLabel();
        keuangan = new javax.swing.JLabel();
        report = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        label_nim = new javax.swing.JLabel();
        text_username = new javax.swing.JTextField();
        label_nim1 = new javax.swing.JLabel();
        text_nm = new javax.swing.JTextField();
        text_dept = new javax.swing.JTextField();
        label_nim2 = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        label_nim3 = new javax.swing.JLabel();
        label_nim4 = new javax.swing.JLabel();
        label_nim5 = new javax.swing.JLabel();
        label_nim6 = new javax.swing.JLabel();
        combo_hak_akses = new javax.swing.JComboBox<>();
        text_password = new javax.swing.JPasswordField();
        text_password2 = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_karyawan = new javax.swing.JTable();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        text_search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(46, 54, 117));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/welcome.png"))); // NOI18N

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Tambah Data Pegawai");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Welcome, ");

        home.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        tambahDataPegawai.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tambahDataPegawai.setForeground(new java.awt.Color(255, 255, 255));
        tambahDataPegawai.setText("Tambah Data Pegawai");
        tambahDataPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahDataPegawaiMouseClicked(evt);
            }
        });

        personalia.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        personalia.setForeground(new java.awt.Color(255, 255, 255));
        personalia.setText("Personalia");
        personalia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personaliaMouseClicked(evt);
            }
        });

        farmasi.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        farmasi.setForeground(new java.awt.Color(255, 255, 255));
        farmasi.setText("Farmasi");
        farmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                farmasiMouseClicked(evt);
            }
        });

        keuangan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        keuangan.setForeground(new java.awt.Color(255, 255, 255));
        keuangan.setText("Keuangan");
        keuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keuanganMouseClicked(evt);
            }
        });

        report.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setText("Report");
        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tambahDataPegawai)
                        .addGap(28, 28, 28)
                        .addComponent(personalia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(farmasi)
                        .addGap(26, 26, 26)
                        .addComponent(keuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home)
                    .addComponent(tambahDataPegawai)
                    .addComponent(personalia)
                    .addComponent(farmasi)
                    .addComponent(keuangan)
                    .addComponent(report))
                .addGap(13, 13, 13))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tambah Data Karyawan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(46, 54, 117))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(1, 50, 67));

        label_nim.setBackground(new java.awt.Color(46, 54, 117));
        label_nim.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim.setForeground(new java.awt.Color(46, 54, 117));
        label_nim.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim.setText("Username");

        text_username.setForeground(new java.awt.Color(46, 54, 117));
        text_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usernameActionPerformed(evt);
            }
        });

        label_nim1.setBackground(new java.awt.Color(46, 54, 117));
        label_nim1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim1.setForeground(new java.awt.Color(46, 54, 117));
        label_nim1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim1.setText("Nama Karyawan");

        text_nm.setForeground(new java.awt.Color(46, 54, 117));
        text_nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nmActionPerformed(evt);
            }
        });

        text_dept.setForeground(new java.awt.Color(46, 54, 117));
        text_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_deptActionPerformed(evt);
            }
        });

        label_nim2.setBackground(new java.awt.Color(46, 54, 117));
        label_nim2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim2.setForeground(new java.awt.Color(46, 54, 117));
        label_nim2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim2.setText("Departemen");

        text_email.setForeground(new java.awt.Color(46, 54, 117));
        text_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_emailActionPerformed(evt);
            }
        });

        label_nim3.setBackground(new java.awt.Color(46, 54, 117));
        label_nim3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim3.setForeground(new java.awt.Color(46, 54, 117));
        label_nim3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim3.setText("Email");

        label_nim4.setBackground(new java.awt.Color(46, 54, 117));
        label_nim4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim4.setForeground(new java.awt.Color(46, 54, 117));
        label_nim4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim4.setText("Hak Akses");

        label_nim5.setBackground(new java.awt.Color(46, 54, 117));
        label_nim5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim5.setForeground(new java.awt.Color(46, 54, 117));
        label_nim5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim5.setText("Password");

        label_nim6.setBackground(new java.awt.Color(46, 54, 117));
        label_nim6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim6.setForeground(new java.awt.Color(46, 54, 117));
        label_nim6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim6.setText("Retype Password");

        combo_hak_akses.setForeground(new java.awt.Color(46, 54, 117));
        combo_hak_akses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "User" }));

        text_password.setForeground(new java.awt.Color(46, 54, 117));

        text_password2.setForeground(new java.awt.Color(46, 54, 117));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_username, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(text_nm, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(text_dept, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(text_email, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(combo_hak_akses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text_password)
                    .addComponent(text_password2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_username, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nim3)
                    .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nim4)
                    .addComponent(combo_hak_akses, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nim5)
                    .addComponent(text_password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nim6)
                    .addComponent(text_password2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabel Data Karyawan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(46, 54, 117))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(1, 50, 67));

        tabel_karyawan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabel_karyawan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tabel_karyawan.setForeground(new java.awt.Color(46, 54, 117));
        tabel_karyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Nama Karyawan", "Departemen", "Email", "Hak Akses", "Password", "Retype Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_karyawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_karyawan);

        saveBtn.setBackground(new java.awt.Color(46, 54, 117));
        saveBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.setPreferredSize(new java.awt.Dimension(65, 32));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(46, 54, 117));
        updateBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(46, 54, 117));
        deleteBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(46, 54, 117));
        resetBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        text_search.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        text_search.setForeground(new java.awt.Color(46, 54, 117));
        text_search.setText("Search...");
        text_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_searchMouseClicked(evt);
            }
        });
        text_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_search)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_usernameActionPerformed

    private void text_nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nmActionPerformed

    private void text_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_deptActionPerformed

    private void text_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_emailActionPerformed

    private void text_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_searchActionPerformed
         pencarian_karyawan();
    }//GEN-LAST:event_text_searchActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Form_Menu_Admin rgs = new Form_Menu_Admin();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void tambahDataPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahDataPegawaiMouseClicked
        Form_Tambah_Data_Pegawai rgs = new Form_Tambah_Data_Pegawai();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_tambahDataPegawaiMouseClicked

    private void personaliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personaliaMouseClicked
        Form_Personalia rgs = new Form_Personalia();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_personaliaMouseClicked

    private void farmasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_farmasiMouseClicked
        Form_Farmasi rgs = new Form_Farmasi();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_farmasiMouseClicked

    private void keuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keuanganMouseClicked
        Form_Keuangan rgs = new Form_Keuangan();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_keuanganMouseClicked

    private void reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseClicked
        Form_Report rgs = new Form_Report();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_reportMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String username = "", namaKaryawan = "", departemen = "", email = "", hakAkses = "", password = "", retypePassword = "";

        username = text_username.getText();
        namaKaryawan = text_nm.getText();
        departemen = text_dept.getText();
        email = text_email.getText();
        hakAkses = (String) combo_hak_akses.getSelectedItem();
        password = text_password.getText();
        retypePassword = text_password2.getText();

        con = connection.getConnection();
        try {
            String sql = "insert into tabel_pegawai values (?,?,?,?,?,?,?)";
            PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);

            stat.setString(1, username);
            stat.setString(2, namaKaryawan);
            stat.setString(3, departemen);
            stat.setString(4, email);
            stat.setString(5, hakAkses);
            stat.setString(6, password);
            stat.setString(7, retypePassword);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Menyimpan data BERHASIL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            reset();
            tampil_tabel_karyawan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menyimpan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        con = connection.getConnection();
        String username = "", namaKaryawan = "", departemen = "", email = "", hakAkses = "", password = "", retypePassword = "";

        username = text_username.getText();
        namaKaryawan = text_nm.getText();
        departemen = text_dept.getText();
        email = text_email.getText();
        hakAkses = (String) combo_hak_akses.getSelectedItem();
        password = text_password.getText();
        retypePassword = text_password2.getText();

        if (email == null) {
            JOptionPane.showMessageDialog(null, "Silahkan isi E-mail anda", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String sql = "update tabel_pegawai set namaKaryawan=?, departemen=?, email=?, hakAkses=?, password=?, retypePassword=? where username='" + username + "'";
            java.sql.PreparedStatement stat = null;
            try {
                stat = con.prepareStatement(sql);
                stat.setString(1, namaKaryawan);
                stat.setString(2, departemen);
                stat.setString(3, email);
                stat.setString(4, hakAkses);
                stat.setString(5, password);
                stat.setString(6, retypePassword);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data BERHASIL di Ubah");
                tampil_tabel_karyawan();
                reset();
            } catch (SQLException se) {
                JOptionPane.showMessageDialog(null, "Data GAGAL di Ubah");
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int baris = tabel_karyawan.getSelectedRow();
        String username = tabmode.getValueAt(baris, 0).toString();
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data username: " + username + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                con = connection.getConnection();
                String sql = "delete from tabel_pegawai where username='" + username + "'";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil di hapus");
                tampil_tabel_karyawan();
                reset();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal di hapus");
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        reset();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void tabel_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_karyawanMouseClicked
        kliktable();
    }//GEN-LAST:event_tabel_karyawanMouseClicked

    private void text_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_searchMouseClicked
        text_search.setText("");
    }//GEN-LAST:event_text_searchMouseClicked
public void pencarian_karyawan() {
        String cari = text_search.getText();

        Object[] Baris = {"username", "namaKaryawan", "departemen", "email", "hakAkses", "password", "retypePassword"};
        tabmode = new DefaultTableModel(null, Baris);
        tabel_karyawan.setModel(tabmode);

        con = connection.getConnection();

        try {
            String sql = "Select * from tabel_pegawai where "
                    + "username like '%" + cari + "%' "
                    + "OR namaKaryawan like '%" + cari + "%' "
                    + "OR departemen like '%" + cari + "%' "
                    + "OR email like '%" + cari + "%' "
                    + "OR hakAkses like '%" + cari + "%' "
                    + "OR password like '%" + cari + "%' "
                    + "OR retypePassword like '%" + cari + "%' "
                    + "order by username asc";
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                String username = rslt.getString("username");
                String namaKaryawan = rslt.getString("namaKaryawan");
                String departemen = rslt.getString("departemen");
                String email = rslt.getString("email");
                String hakAkses = rslt.getString("hakAkses");
                String password = rslt.getString("password");
                String retypePassword = rslt.getString("retypePassword");

                String[] dataField = {username, namaKaryawan, departemen, email, hakAkses, password, retypePassword};
                tabmode.addRow(dataField);
            }
        } catch (Exception ex) {
        }
    }

    public void reset() {
        text_username.setText("");
        text_nm.setText("");
        text_dept.setText("");
        text_email.setText("");
        combo_hak_akses.setSelectedItem("Select");
        text_password.setText("");
        text_password2.setText("");
    }

    private void kliktable() {
        int baris = tabel_karyawan.getSelectedRow();
        text_username.setText((String) tabel_karyawan.getValueAt(baris, 0));
        text_nm.setText((String) tabel_karyawan.getValueAt(baris, 1));
        text_email.setText((String) tabel_karyawan.getValueAt(baris, 2));
        text_email.setText((String) tabel_karyawan.getValueAt(baris, 3));
        combo_hak_akses.setSelectedItem((String) tabel_karyawan.getValueAt(baris, 4));
        text_password.setText((String) tabel_karyawan.getValueAt(baris, 5));
        text_password2.setText((String) tabel_karyawan.getValueAt(baris, 6));
    }

    private DefaultTableModel tabmode;

    public void tampil_tabel_karyawan() {
        Object[] baris = {"username", "namaKaryawan", "departemen", "email", "hakAkses", "password", "retypePassword"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_karyawan.setModel(tabmode);
        con = connection.getConnection();
        try {
            String sql = "select * from tabel_pegawai order by username asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet rslt = stat.executeQuery(sql);
            while (rslt.next()) {
                String username = rslt.getString("username");
                String namaKaryawan = rslt.getString("namaKaryawan");
                String departemen = rslt.getString("departemen");
                String email = rslt.getString("email");
                String hakAkses = rslt.getString("hakAkses");
                String password = rslt.getString("password");
                String retypePassword = rslt.getString("retypePassword");
                String[] data = {username, namaKaryawan, departemen, email, hakAkses, password, retypePassword};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Tambah_Data_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Tambah_Data_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Tambah_Data_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Tambah_Data_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Tambah_Data_Pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_hak_akses;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel farmasi;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel keuangan;
    private javax.swing.JLabel label_nim;
    private javax.swing.JLabel label_nim1;
    private javax.swing.JLabel label_nim2;
    private javax.swing.JLabel label_nim3;
    private javax.swing.JLabel label_nim4;
    private javax.swing.JLabel label_nim5;
    private javax.swing.JLabel label_nim6;
    private javax.swing.JLabel personalia;
    private javax.swing.JLabel report;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable tabel_karyawan;
    private javax.swing.JLabel tambahDataPegawai;
    private javax.swing.JTextField text_dept;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_nm;
    private javax.swing.JPasswordField text_password;
    private javax.swing.JPasswordField text_password2;
    private javax.swing.JTextField text_search;
    private javax.swing.JTextField text_username;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
