/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_Kelola;

import Connection.connection;
import Form_Menu.Form_Menu_Admin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luckycious
 */
public class Form_Keuangan extends javax.swing.JFrame {

    public Connection con;
    public PreparedStatement pst;
    
    public Form_Keuangan() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampil_tabel_keuangan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        tambahDataPegawai = new javax.swing.JLabel();
        Personalia = new javax.swing.JLabel();
        Farmasi = new javax.swing.JLabel();
        Keuangan = new javax.swing.JLabel();
        Report = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        label_nim = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();
        label_nim1 = new javax.swing.JLabel();
        text_nm = new javax.swing.JTextField();
        text_jenis = new javax.swing.JTextField();
        label_nim2 = new javax.swing.JLabel();
        text_pemasukan = new javax.swing.JTextField();
        label_nim3 = new javax.swing.JLabel();
        label_nim4 = new javax.swing.JLabel();
        text_pengeluaran = new javax.swing.JTextField();
        label_nim5 = new javax.swing.JLabel();
        text_tgl = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_keuangan = new javax.swing.JTable();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        text_search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(46, 54, 117));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/welcome.png"))); // NOI18N

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Tambah Data Keuangan");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Welcome, ");

        home.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        tambahDataPegawai.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tambahDataPegawai.setForeground(new java.awt.Color(255, 255, 255));
        tambahDataPegawai.setText("Tambah Data Pegawai");
        tambahDataPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahDataPegawaiMouseClicked(evt);
            }
        });

        Personalia.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Personalia.setForeground(new java.awt.Color(255, 255, 255));
        Personalia.setText("Personalia");
        Personalia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonaliaMouseClicked(evt);
            }
        });

        Farmasi.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Farmasi.setForeground(new java.awt.Color(255, 255, 255));
        Farmasi.setText("Farmasi");
        Farmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FarmasiMouseClicked(evt);
            }
        });

        Keuangan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Keuangan.setForeground(new java.awt.Color(255, 255, 255));
        Keuangan.setText("Keuangan");
        Keuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeuanganMouseClicked(evt);
            }
        });

        Report.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Report.setForeground(new java.awt.Color(255, 255, 255));
        Report.setText("Report");
        Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tambahDataPegawai)
                        .addGap(28, 28, 28)
                        .addComponent(Personalia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Farmasi)
                        .addGap(26, 26, 26)
                        .addComponent(Keuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home)
                    .addComponent(tambahDataPegawai)
                    .addComponent(Personalia)
                    .addComponent(Farmasi)
                    .addComponent(Keuangan)
                    .addComponent(Report))
                .addGap(13, 13, 13))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tambah Data Keuangan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(46, 54, 117))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(1, 50, 67));

        label_nim.setBackground(new java.awt.Color(46, 54, 117));
        label_nim.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim.setForeground(new java.awt.Color(46, 54, 117));
        label_nim.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim.setText("ID Transaksi");

        text_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idActionPerformed(evt);
            }
        });

        label_nim1.setBackground(new java.awt.Color(46, 54, 117));
        label_nim1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim1.setForeground(new java.awt.Color(46, 54, 117));
        label_nim1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim1.setText("Nama Transaksi");

        text_nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nmActionPerformed(evt);
            }
        });

        text_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_jenisActionPerformed(evt);
            }
        });

        label_nim2.setBackground(new java.awt.Color(46, 54, 117));
        label_nim2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim2.setForeground(new java.awt.Color(46, 54, 117));
        label_nim2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim2.setText("Jenis Transaksi");

        text_pemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_pemasukanActionPerformed(evt);
            }
        });

        label_nim3.setBackground(new java.awt.Color(46, 54, 117));
        label_nim3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim3.setForeground(new java.awt.Color(46, 54, 117));
        label_nim3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim3.setText("Total Pemasukan");

        label_nim4.setBackground(new java.awt.Color(46, 54, 117));
        label_nim4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim4.setForeground(new java.awt.Color(46, 54, 117));
        label_nim4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim4.setText("Total Pengeluaran");

        text_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_pengeluaranActionPerformed(evt);
            }
        });

        label_nim5.setBackground(new java.awt.Color(46, 54, 117));
        label_nim5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_nim5.setForeground(new java.awt.Color(46, 54, 117));
        label_nim5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim5.setText("Tanggal Transaksi");

        text_tgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tglActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_nm, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_pemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_pemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabel Data Keuangan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(46, 54, 117))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(1, 50, 67));

        tabel_keuangan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabel_keuangan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tabel_keuangan.setForeground(new java.awt.Color(46, 54, 117));
        tabel_keuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Transaksi", "Nama Transaksi", "Jenis Transaksi", "Total Pemasukan", "Total Pengeluaran", "Tanggal Pengeluaran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel_keuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_keuanganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_keuangan);

        saveBtn.setBackground(new java.awt.Color(46, 54, 117));
        saveBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.setPreferredSize(new java.awt.Dimension(65, 32));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(46, 54, 117));
        updateBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(46, 54, 117));
        deleteBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(46, 54, 117));
        resetBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        text_search.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        text_search.setForeground(new java.awt.Color(46, 54, 117));
        text_search.setText("Search...");
        text_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_searchMouseClicked(evt);
            }
        });
        text_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addComponent(text_search)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idActionPerformed

    private void text_nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nmActionPerformed

    private void text_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_jenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_jenisActionPerformed

    private void text_pemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_pemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_pemasukanActionPerformed

    private void text_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_pengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_pengeluaranActionPerformed

    private void text_tglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tglActionPerformed

    private void text_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_searchActionPerformed
       
        pencarian_keuangan();
    }//GEN-LAST:event_text_searchActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Form_Menu_Admin rgs = new Form_Menu_Admin();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void tambahDataPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahDataPegawaiMouseClicked
        Form_Tambah_Data_Pegawai rgs = new Form_Tambah_Data_Pegawai();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_tambahDataPegawaiMouseClicked

    private void PersonaliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonaliaMouseClicked
        Form_Personalia rgs = new Form_Personalia();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_PersonaliaMouseClicked

    private void FarmasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FarmasiMouseClicked
        Form_Farmasi rgs = new Form_Farmasi();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_FarmasiMouseClicked

    private void KeuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeuanganMouseClicked
        Form_Keuangan rgs = new Form_Keuangan();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_KeuanganMouseClicked

    private void ReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportMouseClicked
        Form_Report rgs = new Form_Report();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_ReportMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String idTransaksi = "", namaTransaksi = "", jenisTransaksi = "", totalPemasukan = "", totalPengeluaran = "", tanggalTransaksi = "";

        idTransaksi = text_id.getText();
        namaTransaksi = text_nm.getText();
        jenisTransaksi = text_jenis.getText();
        totalPemasukan = text_pemasukan.getText();
        totalPengeluaran = text_pengeluaran.getText();
        tanggalTransaksi = text_tgl.getText();

        con = connection.getConnection();
        try {
            String sql = "insert into tabel_keuangan values (?,?,?,?,?,?)";
            PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);

            stat.setString(1, idTransaksi);
            stat.setString(2, namaTransaksi);
            stat.setString(3, jenisTransaksi);
            stat.setString(4, totalPemasukan);
            stat.setString(5, totalPengeluaran);
            stat.setString(6, tanggalTransaksi);
            
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Menyimpan data BERHASIL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            reset();
            tampil_tabel_keuangan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menyimpan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        con = connection.getConnection();
        String idTransaksi = "", namaTransaksi = "", jenisTransaksi = "", totalPemasukan = "", totalPengeluaran = "", tanggalTransaksi = "";

        idTransaksi = text_id.getText();
        namaTransaksi = text_nm.getText();
        jenisTransaksi = text_jenis.getText();
        totalPemasukan = text_pemasukan.getText();
        totalPengeluaran = text_pengeluaran.getText();
        tanggalTransaksi = text_tgl.getText();
       
       

        if (namaTransaksi == null) {
            JOptionPane.showMessageDialog(null, "Silahkan isi Nama Produk anda", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String sql = "update tabel_keuangan set namaTransaksi=?, jenisTransaksi=?, totalPemasukan=?, totalPengeluaran=?, tanggalTransaksi=? where idTransaksi='" + idTransaksi + "'";
            java.sql.PreparedStatement stat = null;
            try {
                stat = con.prepareStatement(sql);
                stat.setString(1, namaTransaksi);
                stat.setString(2, jenisTransaksi);
                stat.setString(3, totalPemasukan);
                stat.setString(4, totalPengeluaran);
                stat.setString(5, tanggalTransaksi);
               
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data BERHASIL di Ubah");
                tampil_tabel_keuangan();
                reset();
            } catch (SQLException se) {
                JOptionPane.showMessageDialog(null, "Data GAGAL di Ubah");
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
         int baris = tabel_keuangan.getSelectedRow();
        String idTransaksi = tabmode.getValueAt(baris, 0).toString();
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data idTransaksi: " + idTransaksi + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                con = connection.getConnection();
                String sql = "delete from tabel_keuangan where idTransaksi='" + idTransaksi + "'";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil di hapus");
                tampil_tabel_keuangan();
                reset();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal di hapus");
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        reset();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void text_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_searchMouseClicked
        text_search.setText("");
        
    }//GEN-LAST:event_text_searchMouseClicked

    private void tabel_keuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_keuanganMouseClicked
        kliktable();
    }//GEN-LAST:event_tabel_keuanganMouseClicked

     public void pencarian_keuangan() {
        String cari = text_search.getText();

        Object[] Baris = {"idTransaksi", "namaTransaksi", "jenisTransaksi", "totalPemasukan", "totalPengeluaran", "tanggalTransaksi"};
        tabmode = new DefaultTableModel(null, Baris);
        tabel_keuangan.setModel(tabmode);

        con = connection.getConnection();

        try {
            String sql = "Select * from tabel_keuangan where "
                    + "idTransaksi like '%" + cari + "%' "
                    + "OR namaTransaksi like '%" + cari + "%' "
                    + "OR jenisTransaksi like '%" + cari + "%' "
                    + "OR totalPemasukan like '%" + cari + "%' "
                    + "OR totalPengeluaran like '%" + cari + "%' "
                    + "OR tanggalTransaksi like '%" + cari + "%' "
                    + "order by idTransaksi asc";
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                String idTransaksi = rslt.getString("idTransaksi");
                String namaTransaksi = rslt.getString("namaTransaksi");
                String jenisTransaksi = rslt.getString("jenisTransaksi");
                String totalPemasukan = rslt.getString("totalPemasukan");
                String totalPengeluaran = rslt.getString("totalPengeluaran");
                String tanggalTransaksi = rslt.getString("tanggalTransaksi");
       

                String[] dataField = {idTransaksi, namaTransaksi, jenisTransaksi, totalPemasukan, totalPengeluaran, tanggalTransaksi};
                tabmode.addRow(dataField);
            }
        } catch (Exception ex) {
        }
    }

    public void reset() {
        text_id.setText("");
        text_nm.setText("");
        text_jenis.setText("");
        text_pemasukan.setText("");
        text_pengeluaran.setText("");
        text_tgl.setText("");
    }

    private void kliktable() {
        int baris = tabel_keuangan.getSelectedRow();
        text_id.setText((String) tabel_keuangan.getValueAt(baris, 0));
        text_nm.setText((String) tabel_keuangan.getValueAt(baris, 1));
        text_jenis.setText((String) tabel_keuangan.getValueAt(baris, 2));
        text_pemasukan.setText((String) tabel_keuangan.getValueAt(baris, 3));
        text_pengeluaran.setText((String) tabel_keuangan.getValueAt(baris, 4));
        text_tgl.setText((String) tabel_keuangan.getValueAt(baris, 5));
        
    }

    private DefaultTableModel tabmode;

    public void tampil_tabel_keuangan() {
        Object[] baris = {"idTransaksi", "namaTransaksi", "jenisTransaksi", "totalPemasukan", "totalPengeluaran", "tanggalTransaksi"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_keuangan.setModel(tabmode);
        con = connection.getConnection();
        try {
            String sql = "select * from tabel_keuangan order by idTransaksi asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet rslt = stat.executeQuery(sql);
            while (rslt.next()) {
                String idTransaksi = rslt.getString("idTransaksi");
                String namaTransaksi = rslt.getString("namaTransaksi");
                String jenisTransaksi = rslt.getString("jenisTransaksi");
                String totalPemasukan = rslt.getString("totalPemasukan");
                String totalPengeluaran = rslt.getString("totalPengeluaran");
                String tanggalTransaksi = rslt.getString("tanggalTransaksi");
               
            
                String[] data = {idTransaksi, namaTransaksi, jenisTransaksi, totalPemasukan, totalPengeluaran, tanggalTransaksi};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Keuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Keuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Keuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Keuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Keuangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Farmasi;
    private javax.swing.JLabel Keuangan;
    private javax.swing.JLabel Personalia;
    private javax.swing.JLabel Report;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_nim;
    private javax.swing.JLabel label_nim1;
    private javax.swing.JLabel label_nim2;
    private javax.swing.JLabel label_nim3;
    private javax.swing.JLabel label_nim4;
    private javax.swing.JLabel label_nim5;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable tabel_keuangan;
    private javax.swing.JLabel tambahDataPegawai;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_jenis;
    private javax.swing.JTextField text_nm;
    private javax.swing.JTextField text_pemasukan;
    private javax.swing.JTextField text_pengeluaran;
    private javax.swing.JTextField text_search;
    private javax.swing.JTextField text_tgl;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
